--хгцкедх
CREATE VIEW BUS_INFO
AS
SELECT E.SECTOR,E.BUSSTATIONNAME,B.LINE
FROM FN72008.EMBARK E, FN72008.BUSES B
WHERE B.REGISTARTIONNUMBER=E.BUSESREGISTRATIONNUMBER@

SELECT * FROM FN72008.BUS_INFO@

CREATE OR REPLACE VIEW K_BUSSTATION
AS
SELECT TIMEOFEMBARKING,SECTOR, BUSSTATIONNAME
FROM FN72008.EMBARK
WHERE BUSSTATIONNAME ='юбрнцюпю 21-бх бей'@

SELECT * FROM FN72008.K_BUSSTATION@
