
CREATE TABLE STAFF(
    NAME VARCHAR(255) NOT NULL ,
    SNUM BIGINT NOT NULL  ,
    PHONENUMBER BIGINT,
    OFFICECOMPANY CHAR(100) ,
    PRIMARY KEY (NAME,SNUM),
    TICKETOFFICECOMPANY CHAR(100) NOT NULL REFERENCES TICKETOFFICE(COMPANY)
)@

SELECT * FROM FN72008.STAFF@

CREATE TABLE TICKETOFFICE(
    COMPANY CHAR(100) NOT NULL ,
    OFFICENUMBER INT,
    PRIMARY KEY (COMPANY)
)@


CREATE TABLE PASSENGERS(
    SEATNUMBER INT NOT NULL ,
    NAME VARCHAR(50),
    NUMBEROFCUSTOMERCARD INT,
    PRIMARY KEY (SEATNUMBER)


)@
CREATE TABLE TICKETS(
    TICKETNUMBER INT NOT NULL ,
    PRICE DECIMAL NOT NULL ,
    DIRECTION VARCHAR(30) NOT NULL ,
    PRIMARY KEY (TICKETNUMBER),
    PASSENGERSEATNUMBER INT NOT NULL REFERENCES PASSENGERS(SEATNUMBER),
    BUSESREGISTRATIONNUMBER VARCHAR(20) NOT NULL REFERENCES BUSES(REGISTARTIONNUMBER),
    TICKETOFFICECOMPANY CHAR(100) NOT NULL REFERENCES TICKETOFFICE(COMPANY)
)@
CREATE TABLE BUSES(
    REGISTARTIONNUMBER VARCHAR(20) NOT NULL ,
    LINE VARCHAR(100),
    PRIMARY KEY (REGISTARTIONNUMBER)
)@
CREATE TABLE EMBARK(
    TIMEOFEMBARKING TIME,
    DATEOFEMBARKING DATE,
    SECTOR INT,
    BUSESREGISTRATIONNUMBER VARCHAR(20) NOT NULL REFERENCES BUSES(REGISTARTIONNUMBER),
    BUSSTATIONNAME VARCHAR(100) NOT NULL REFERENCES BUSSTATION(NAME)
)@

CREATE TABLE BUSSTATION(
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(100),
    PRIMARY KEY (NAME)
)@