--процедура с курсор и while цикъл;

CREATE TABLE FN72008.MY_TICKETS(
    PRICE DECIMAL(9,2) ,
    BUSESREGISTRATIONNUMBER VARCHAR(20),
    TICKETOFFICECOMPANY CHAR(100)
    
    )@
    
    CREATE OR REPLACE PROCEDURE FN72008.T_INFO(IN T_TICKETNO INT)
    LANGUAGE SQL
    BEGIN 
    DECLARE E_ERROR INT;
    DECLARE V_PRICE DECIMAL(9,2);
    DECLARE V_BUSESREGISTRATIONNUMBER VARCHAR (20);
    DECLARE V_TICKETOFFICECOMPANY CHAR(100);
    DECLARE AT_END INTEGER DEFAULT 0;
    DECLARE CURSOR1 CURSOR FOR SELECT PRICE,BUSESREGISTRATIONNUMBER,TICKETOFFICECOMPANY FROM FN72008.TICKETS WHERE T_TICKETNO=TICKETNUMBER;
    DECLARE CONTINUE HANDLER FOR SQLSTATE '02000'
SET AT_END=1;

OPEN CURSOR1;
FETCH CURSOR1 INTO V_PRICE,V_BUSESREGISTRATIONNUMBER,V_TICKETOFFICECOMPANY;

IF AT_END=1 THEN
 SET E_ERROR=RAISE_ERROR('70001', 'DONT EXIST TICKET WITH THIS TICKET NUMBER');
END IF;

WHILE AT_END=0 DO
INSERT INTO FN72008.MY_TICKETS(PRICE,BUSESREGISTRATIONNUMBER,TICKETOFFICECOMPANY)
VALUES (V_PRICE,V_BUSESREGISTRATIONNUMBER,V_TICKETOFFICECOMPANY);

FETCH CURSOR1 INTO V_PRICE,V_BUSESREGISTRATIONNUMBER,V_TICKETOFFICECOMPANY;
  END WHILE;
  CLOSE CURSOR1;  
    
    
    END@
    
    CALL  FN72008.T_INFO('28976')@
    CALL FN72008.T_INFO('0')@
    SELECT * FROM FN72008.MY_TICKETS@
    ----------------------------------------------------------

--процедура с прихващане на изключение;
CREATE OR REPLACE PROCEDURE FN72008.P_INFO(IN P_SEATNO INT, OUT P_SQLSTATE CHAR(5),OUT P_SQLCODE INTEGER)
LANGUAGE SQL
BEGIN
DECLARE E_ERROR INT;
DECLARE V_NAME VARCHAR(50);
DECLARE V_NUM_CARD INT;
DECLARE AT_END INTEGER DEFAULT 0;
DECLARE SQLCODE INTEGER DEFAULT 0;
DECLARE SQLSTATE CHAR (5) DEFAULT '00000';
DECLARE CURSOR1 CURSOR FOR SELECT NAME,NUMBEROFCUSTOMERCARD FROM FN72008.PASSENGERS WHERE SEATNUMBER=P_SEATNO;
DECLARE CONTINUE HANDLER FOR SQLSTATE '02000'
SET AT_END=1;
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT SQLCODE,SQLSTATE INTO P_SQLCODE,P_SQLSTATE
FROM SYSIBM.SYSDUMMY1;

OPEN CURSOR1;
FETCH CURSOR1 INTO V_NAME,V_NUM_CARD;

IF AT_END=1 THEN 
SET E_ERROR=RAISE_ERROR('70001', 'NO PASSENGER WITH THIS SEATNO');
END IF;

WHILE AT_END=0 DO
INSERT INTO FN72008.P_PASSENGER(NAME ,NUMBEROFCUSTOMERCARD )
VALUES (V_NAME,V_NUM_CARD);
FETCH CURSOR1 INTO V_NAME,V_NUM_CARD;
END WHILE;
CLOSE CURSOR1;
END@

SELECT * FROM FN72008.P_PASSENGER@

DROP TABLE FN72008.DELETED_PASSENGER@
CREATE TABLE FN72008.P_PASSENGER(
    
    NAME VARCHAR(50),
    NUMBEROFCUSTOMERCARD INT
    )@

----------------------------------------
--процедура с курсор и входни и изходни параметри;
CREATE OR REPLACE PROCEDURE FN72008.PASSENGER_INFO(IN P_SEATNO INT, OUT P_NAME VARCHAR(50))
LANGUAGE SQL
BEGIN 

DECLARE C1 CURSOR FOR SELECT NAME FROM FN72008.PASSENGERS WHERE SEATNUMBER=P_SEATNO;
OPEN C1;
FETCH C1 INTO P_NAME;

END@

SELECT * FROM FN72008.PASSENGERS
