
set schema fn72008@


CREATE OR REPLACE PROCEDURE FN72008.SALARY (IN P_EMPNO CHAR(6), OUT SALARY DECIMAL(9,2))
LANGUAGE SQL
BEGIN 
DECLARE C1 CURSOR FOR SELECT SALARY FROM FN72008.EMP WHERE EMPNO=P_EMPNO;
OPEN C1;
FETCH C1 INTO SALARY;

END@

CREATE or replace PROCEDURE FN72008.RAISE_FOR_2022 (IN P_EMPNO CHAR(6),
OUT P_NEW_SALARY DECIMAL(9,2))
LANGUAGE SQL
SPECIFIC RAISE_FOR_2022
SL: BEGIN

DECLARE MIN_SAL INT DEFAULT 100000;
DECLARE OLD_SALARY INT DEFAULT 0;

CALL FN72008.SALARY(P_EMPNO,OLD_SALARY);

IF (OLD_SALARY <= MIN_SAL)
THEN
SET P_NEW_SALARY = OLD_SALARY+5000 ;
ELSE
SET P_NEW_SALARY = OLD_SALARY;
END IF;
END SL@


